"""
rag/document_store.py — Document indexing pipeline for CompanionOS RAG.

Orchestrates the full upload-to-index pipeline:
  1. Detect file type from filename extension.
  2. Route to the correct parser (PDF, DOCX, TXT/MD) to extract text.
  3. Chunk the text into overlapping segments.
  4. Embed each chunk via the Gemini embedding model.
  5. Upsert chunks + embeddings into ChromaDB.

Chunk params (size, overlap) are read from settings so they can be tuned
without redeploying code.
"""

from __future__ import annotations
import logging
from pathlib import Path
from typing import Optional, Tuple

from .parsers import extract_chunks
from .embedder import embed_chunks
from .vector_store import upsert_chunks
from ..config import get_settings

logger = logging.getLogger(__name__)


def detect_file_type(filename: str) -> str:
    """
    Infers file type from the filename extension.

    Returns a lowercase extension without leading dot.
    Falls back to "txt" for unrecognised or missing extensions.
    """
    suffix = Path(filename).suffix.lower().lstrip(".")
    if suffix in ("pdf", "docx", "doc", "txt", "md", "markdown"):
        return suffix
    if suffix:
        logger.warning("Unrecognised file type '.%s' for %s — treating as txt", suffix, filename)
    return "txt"


async def index_document(
    workspace_id: str,
    doc_id: str,
    filename: str,
    file_bytes: bytes,
    file_type: Optional[str] = None,
    chunk_size: Optional[int] = None,
    overlap: Optional[int] = None,
) -> Tuple[int, int]:
    """
    Runs the complete parse → chunk → embed → index pipeline for one document.

    Args:
        workspace_id: Target workspace UUID.
        doc_id:       Document UUID (generated by the caller before indexing).
        filename:     Original filename — used to auto-detect type if file_type is None.
        file_bytes:   Raw file bytes from the upload.
        file_type:    Explicit file type override. If None, inferred from filename.
        chunk_size:   Characters per chunk. Defaults to settings.rag_chunk_size (500).
        overlap:      Overlap between consecutive chunks. Defaults to settings.rag_chunk_overlap (50).

    Returns:
        Tuple of (chunks_extracted, chunks_indexed). They may differ if the
        embed call fails (in which case chunks_indexed is 0).

    Raises:
        Exception: Propagated from parsers on parse failure. Embed errors are
                   handled gracefully at the chunk level.
    """
    settings = get_settings()
    ft = file_type or detect_file_type(filename)
    cs = chunk_size if chunk_size is not None else settings.rag_chunk_size
    ov = overlap if overlap is not None else settings.rag_chunk_overlap

    # Step 1: Parse and chunk
    chunks = extract_chunks(file_bytes, ft, chunk_size=cs, overlap=ov)
    chunk_count = len(chunks)
    logger.info("Parsed %d chunks from '%s' (type=%s, chunk_size=%d)", chunk_count, filename, ft, cs)

    if not chunks:
        logger.warning("No text extracted from '%s' — document not indexed", filename)
        return 0, 0

    # Step 2: Embed all chunks
    embeddings = await embed_chunks(chunks)
    embedded_count = len(embeddings)

    if not embeddings:
        logger.error("All chunk embeddings failed for '%s' — document not indexed", filename)
        return chunk_count, 0

    # Step 3: Align chunks → embeddings (embed_chunks skips empty/failed chunks,
    #         so take only the first embedded_count chunks to keep lengths in sync).
    valid_chunks = chunks[:embedded_count]

    upserted = upsert_chunks(workspace_id, doc_id, filename, valid_chunks, embeddings)
    logger.info(
        "Indexed doc=%s workspace=%s: %d/%d chunks embedded, %d upserted",
        doc_id, workspace_id, embedded_count, chunk_count, upserted,
    )
    return chunk_count, upserted
